[package]
name = "lxd2-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = "2"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
fontdue = "0.9"
pulldown-cmark = { version = "0.12", default-features = false }
qrcode = { version = "0.14", default-features = false }
