[package]
name = "lxd2"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
lxd2-core = { path = "../lxd2-core" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
btleplug = "0.11"
futures = "0.3"
image = "0.25"
